

@rootUrl = http://localhost:8000


GET {{rootUrl}}




### Auth API  post new user
# sessionId=68304655eaf0518641ff2677&t=7d012619-cf8d-4764-b516-e39f9c8e580f


## Auth Route api

### Posting new user

POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fName":"Shankar",
    "lName":"Pandey",
    "email":"ba1a23@gmail.com",
    "phone":"0101",
    "password":"Asdf!23456"
 

}


### post to activate user

POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
   "sessionId":"68314791cc4dfe14aff6ed82",
   "t":"f66560eb-ed24-417a-b507-f750b75"
 

}

# activate-user?sessionId=68314791cc4dfe14aff6ed82&t=f66560eb-ed24-417a-b507-f750b7546e10



####Login user

POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email":"ba1a23@gmail.com",
    "password":"Asdf!23456"
 

}


####Get user profiles

GET {{rootUrl}}/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhMWEyM0BnbWFpbC5jb20iLCJpYXQiOjE3NDkzOTE0MzQsImV4cCI6MTc0OTM5MTQ5NH0.BLIdGnd9fvGAIpBofQ8J2mX7A2xfsiZli8NdkLr2CY4



GET {{rootUrl}}/api/v1/auth/renew-jwt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhMWEyM0BnbWFpbC5jb20iLCJpYXQiOjE3NDg5MTYyNTgsImV4cCI6MTc1MTUwODI1OH0.pY6myAmxBGys1AeoAtPVlpVv6e39LyuuZXaYCJV25wQ


### OTP REQUEST

POST {{rootUrl}}/api/v1/auth/otp
Content-Type: application/json

{
    "email":"ba1a23@gmail.com"
}